name: projectblog
description: A new Flutter blog project.

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Please adjust this to match your Flutter SDK version if needed

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  cloud_firestore: ^4.9.1
  firebase_storage: ^11.2.6

  # State management
  get: ^4.6.5
  get_storage: ^2.1.1

  # Storage
  shared_preferences: ^2.2.1

  # UI
  google_fonts: ^5.1.0
  flutter_svg: ^2.0.7
  cached_network_image: ^3.2.3
  image_picker: ^1.0.4

  # Others
  intl: ^0.18.1
  http: ^1.1.0
  google_sign_in: ^7.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  
  # Add this section to include your assets
  assets:
    - assets/images/
    - assets/videos/