// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCG7-My9GRJvWs0eIfqxnbAqsTbudr3jJo',
    appId: '1:97241370595:web:7446a771b228fbf8169ad6',
    messagingSenderId: '97241370595',
    projectId: 'projectblog-d5bbc',
    authDomain: 'projectblog-d5bbc.firebaseapp.com',
    databaseURL: 'https://projectblog-d5bbc-default-rtdb.firebaseio.com',
    storageBucket: 'projectblog-d5bbc.firebasestorage.app',
    measurementId: 'G-1NMZY45ERM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtD3Pvfg2ahs7MzsfjLhv6-l2pTlAKgNI',
    appId: '1:97241370595:android:218b8efb01d5b9ce169ad6',
    messagingSenderId: '97241370595',
    projectId: 'projectblog-d5bbc',
    databaseURL: 'https://projectblog-d5bbc-default-rtdb.firebaseio.com',
    storageBucket: 'projectblog-d5bbc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBp1bLHC__kAQjHtLePbRmSViBzt6QNgjg',
    appId: '1:97241370595:ios:9867908cff753224169ad6',
    messagingSenderId: '97241370595',
    projectId: 'projectblog-d5bbc',
    databaseURL: 'https://projectblog-d5bbc-default-rtdb.firebaseio.com',
    storageBucket: 'projectblog-d5bbc.firebasestorage.app',
    androidClientId: '97241370595-6tlp6no3f0mv0aomo6gch60m66dntgvi.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectblog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBp1bLHC__kAQjHtLePbRmSViBzt6QNgjg',
    appId: '1:97241370595:ios:9867908cff753224169ad6',
    messagingSenderId: '97241370595',
    projectId: 'projectblog-d5bbc',
    databaseURL: 'https://projectblog-d5bbc-default-rtdb.firebaseio.com',
    storageBucket: 'projectblog-d5bbc.firebasestorage.app',
    androidClientId: '97241370595-6tlp6no3f0mv0aomo6gch60m66dntgvi.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectblog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCG7-My9GRJvWs0eIfqxnbAqsTbudr3jJo',
    appId: '1:97241370595:web:9f4d2b32bf933d78169ad6',
    messagingSenderId: '97241370595',
    projectId: 'projectblog-d5bbc',
    authDomain: 'projectblog-d5bbc.firebaseapp.com',
    databaseURL: 'https://projectblog-d5bbc-default-rtdb.firebaseio.com',
    storageBucket: 'projectblog-d5bbc.firebasestorage.app',
    measurementId: 'G-TFHKK2H6TJ',
  );
}
